name: lpr
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - lightning
  - flask
  - werkzeug
  - pip
  - pip:
    - ultralytics
    - easyocr
    - pytesseract
    - timm
    - nltk
    - deep_sort_realtime
