name: lpr
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - lightning
  - pip
pip:
  - ultralytics
  - easyocr
  - pytesseract
  - timm
  - nltk
