name: lpr
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchaudio
  - torchvision
  - lightning
  - flask
  - werkzeug
  - pip
pip:
  - ultralytics
  - easyocr
  - pytesseract
  - timm
  - nltk
