data_path: ./data/test/images
label_path: ./data/test/labels
lpd_checkpoint_path: checkpoints/obb/best.pt
verbose: False
visualize: True
recognizer: 
  type: parseq  # parseq, easyocr, tesseract
  language: en
  parseq_img_size: [32, 128] # [32, 128]
  tesseract_engine: 3 # 0=Legacy, 1=LSTM, 2=Legacy+LSTM 3=default
  tesseract_segmentation: 7 # For single lines
upscaler:
  type: bilinear # LANCZOS4, bilinear, bicubic, GAN
  scale_factor: 2
image_processing:
  grayscale: True
  denoising: True
  normalize: True
  contrast: False
  thresholding: False
  threshold_value: 100
  rotation: True
  max_rotation_angle: 10