data_path: ./data/test/images
label_path: ./data/test/labels
lpd_checkpoint_path: checkpoints/test/LPD_best.pt
verbose: True
visualize: True
recognizer: 
  type: parseq  # parseq, easyocr, tesseract
  language: en
  parseq_img_size: [32, 128]
  tesseract_engine: 3 # 0=Legacy, 1=LSTM, 2=Legacy+LSTM 3=default
  tesseract_segmentation: 7 # For single lines
upscaler:
  type: "LANCZOS4" # LANCZOS4, bilinear, bicubic
  scale_factor: 2
image_processing:
  grayscale: True
  denoising: True
  normalize: True
  contrast: False
  thresholding: False
  threshold_value: 100
  rotation: False
  max_rotation_angle: 10